### PR TITLE
Added Symfony 4 support

### PR DESCRIPTION
**Pull request by novecode**
I have fixed an error that has been throwing before Behat test execution:

> The reserved indicator "%" cannot start a plain scalar; you need to quote the scalar at line 2 (near "autoload: [ %paths.base%/tests/behat/bootstrap ]").

### CODE REVIEW

**Comment by alexdesignworks** [comment]
@novecode
Thank you for contribution. Merged now.

**Comment by OskarStark** [comment]
Did you tested it?

because I get this error: 
`drupal/drupal-extension v3.4.0 requires symfony/dependency-injection ~2.7|~3.0`

Can only install one of: symfony/dependency-injection[v3.4.0, v4.0.9]

Imo Drupal-extension needs to support `symfony/console:^4.0`first (cc @jhedstrom)

**Comment by OskarStark** [comment]
damn, why is `drupal-extension`now required? 🤔

**Comment by jhedstrom** [comment]
The drupal extension can't support `symfony/console:^4.0` because Drupal core requires it at `~3.4.0`.

**Pull request merged**
